# Generated by Django 2.2.3 on 2019-07-31 20:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('oneToMany', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=255)),
                ('clinic_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veterinarian_name', models.CharField(max_length=255)),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='oneToMany.Clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=255)),
                ('breed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='oneToMany.Breed')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='oneToMany.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(default=datetime.datetime(2019, 7, 31, 20, 1, 0, 124887, tzinfo=utc))),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='oneToMany.Pet')),
                ('veterinarian_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veterinarians', to='oneToMany.Veterinarian')),
            ],
        ),
    ]
