# Generated by Django 2.2.3 on 2019-07-31 20:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('oneToMany', '0002_appointment_breed_clinic_owner_pet_veterinarian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Critic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critic_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_name', models.CharField(max_length=255)),
                ('publication_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=255)),
                ('restaurant_address', models.CharField(max_length=255)),
                ('accessible', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 20, 58, 26, 464068, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 7, 31, 20, 58, 26, 465909, tzinfo=utc))),
                ('rating', models.IntegerField()),
                ('critic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critics', to='oneToMany.Critic')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='oneToMany.Restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='critic',
            name='publication_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='oneToMany.Publication'),
        ),
    ]
