# Generated by Django 2.2.3 on 2019-08-01 20:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Films_Watched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(default=datetime.datetime(2019, 8, 1, 20, 36, 36, 122823, tzinfo=utc))),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='manyToMany.Film')),
                ('viewer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='manyToMany.Viewer')),
            ],
        ),
    ]
