# Generated by Django 2.2.3 on 2019-08-01 20:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manyToMany', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films_watched',
            name='appointment_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 1, 20, 51, 50, 761008, tzinfo=utc)),
        ),
    ]
